### PR TITLE
added `source-depth` entry and moved to github sources

### PR DESCRIPTION
**Pull request by soumyaDghosh**
Initial step to enable automation

### CODE REVIEW

**Comment by merlijn-sebrechts** [comment]
I don't think we need to switch to GitHub. Especially because the GitHub mirror doesn't actually track releases. Last release on GitHub was in 2018, while the last release on gitlab was 1 month ago.

You should be able to modify the update script to get the latest release from gitlab instead of GitHub. For example, to get the latest dav1d version: `curl -s https://code.videolan.org/api/v4/projects/198/releases/ | jq '.[0].tag_name' -r`

Let me know if you're stuck on something.

**Comment by soumyaDghosh** [comment]
Well, let me explain the problems to you then. 

1. This snap has many parts, and I can't find any easy way to update all the parts easily using the existing snapcrafters CI.
2. Instead of manually doing things, can we use the [updatesnap.py](https://github.com/ubuntu/desktop-snaps/blob/stable/updatesnap/updatesnap.py) action, a little fixed for snapcrafters?
3. I am also not interested in github sources, but the above said workflow didn't work well with sources other than Github and Gitlab.

To get all the parts, we'll need a very complicated script as much I can think of.

**Comment by jnsgruk** [comment]
In regards to updating multiple parts, you can see one approach here:

https://github.com/snapcrafters/signal-desktop/blob/candidate/.github/workflows/sync-version-with-upstream.yml

**Comment by soumyaDghosh** [comment]
> In regards to updating multiple parts, you can see one approach here:
> 
> https://github.com/snapcrafters/signal-desktop/blob/candidate/.github/workflows/sync-version-with-upstream.yml

Okay.. so, I'll need to use the tar files as sources then..

**Comment by jnsgruk** [comment]
> > In regards to updating multiple parts, you can see one approach here:
> 
> > 
> 
> > https://github.com/snapcrafters/signal-desktop/blob/candidate/.github/workflows/sync-version-with-upstream.yml
> 
> 
> 
> Okay.. so, I'll need to use the tar files as sources then..

Not sure I follow? You can still use git sources and use yq/sed to bump parts accordingly

**Comment by soumyaDghosh** [comment]
> > > In regards to updating multiple parts, you can see one approach here:
> > 
> > 
> > > 
> > 
> > 
> > > https://github.com/snapcrafters/signal-desktop/blob/candidate/.github/workflows/sync-version-with-upstream.yml
> > 
> > 
> > Okay.. so, I'll need to use the tar files as sources then..
> 
> Not sure I follow? You can still use git sources and use yq/sed to bump parts accordingly

Yup..working on it..

**Comment by soumyaDghosh** [comment]
@merlijn-sebrechts @jnsgruk I am directly pushing to the workflow to check how it's working. If it fails, I will reset the head

EDIT: Can't do it anymore :cry:

**Pull request closed without merging**
