### PR TITLE
Move both content and sdk snaps to one single branch

### PR DESCRIPTION
**Pull request by soumyaDghosh**

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
@merlijn-sebrechts we need the core22 branch here first. Then I can push that branch

**Review by merlijn-sebrechts — APPROVED** [review]
LGTM!

I renamed the branch to `2204`, so that we can use the branch name to figure out the snap name in the CI scripts.

**Comment by soumyaDghosh** [comment]
I thought of core22 as branch name, but never mind!

**Comment by soumyaDghosh** [comment]
@merlijn-sebrechts The branch rules also needs to be changed, in order for the CIs to work

**Comment by merlijn-sebrechts** [comment]
Should be fixed now!

**Comment by soumyaDghosh** [comment]
The version line isn't necessary here, anyway to remove it? It's unnecessarily breaking the CI

**Pull request merged**
