### PR TITLE
update for `core24`

### PR DESCRIPTION
**Pull request by soumyaDghosh**
I am not sure though that the builds will work with the CI from the snapcrafters. But, let's give it a try.

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
There is no chance to vulkan to be updated to 1.3.277 soon in the noble repos. I tested this previously with the mesa-2404 content snap, it did work. So, we're building vulkan from source here and shipping it with the content snap.

https://answers.launchpad.net/ubuntu/+source/vulkan-loader/+question/817759

**Comment by jnsgruk** [comment]
Do we need to branch off a 2404 branch here and target that before merging?

**Comment by soumyaDghosh** [comment]
Yeah, I think that'd be better

**Comment by jnsgruk** [comment]
The changes mostly look good to me, and I've targeted the new branch with the PR, but I think we should have two seperate repos for ffmpeg-2204* and ffmpeg-2404*, because otherwise permissions etc. are going to get complicated, and we won't be able to update the older versions easily (like for example if it needs to be rebuilt for a security issue)

**Comment by soumyaDghosh** [comment]
Hi @jnsgruk , as you suggested, I have created this new repository for [`ffmpeg-2204-sdk`](https://github.com/snapcrafters/ffmpeg-2204-sdk). So, this repo can be renamed to `ffmpeg-2404-sdk` and we're good to go. 
Similarly, we can also do the same for webkitgtk

**Comment by jnsgruk** [comment]
Okay - I'm sprinting this week at work so a little light on time, but will try to squeeze it in!

**Review by jnsgruk — APPROVED** [review]

**Pull request merged**
