### PR TITLE
add libdir for dav1d

### PR DESCRIPTION
**Pull request by iomezk**
I'm getting `ERROR: dav1d >= 0.5.0 not found using pkg-config` for ffmpeg part without this patch.
meson version is 0.61.2

### CODE REVIEW

**Comment by soumyaDghosh** [comment]
Is this while building mpv? Or any other app?

Well, first of all, there is no such parameter called `libdir` in dav1d, as much I searched here.

https://code.videolan.org/videolan/dav1d/-/blob/master/meson_options.txt?ref_type=heads

You can look for it here. Try with adding this in the part that's failing

```
build-environment:
  PKG_CONFIG_PATH: /snap/ffmpeg-2204-sdk/current/usr/lib/$CRAFT_ARCH_TRIPLET/pkgconfig
```

**Comment by iomezk** [comment]
> Well, first of all, there is no such parameter called `libdir` in dav1d, as much I searched here.

It's built-in meson option. I tried to build ffmpeg-2004. <s>It is even reproducible</s>

**Comment by soumyaDghosh** [comment]
Meson already uses libdir

```
 soumyaxubuntu  soumyas-gf63-thin-11uc  ~  snap info ffmpeg-2204-sdk
name:      ffmpeg-2204-sdk
summary:   SDK for ffmpeg-2204
publisher: Soumyadeep Ghosh (soumyadghosh)
store-url: https://snapcraft.io/ffmpeg-2204-sdk
license:   unset
description: |
  SDK to build ffmpeg-2204 content snap
snap-id:      uuVEMSpNrsGQSfOcD1TEgLtSgsATN8Jy
tracking:     latest/edge
refresh-date: 47 days ago, at 02:55 IST
channels:
  latest/stable:    0+git.cfe32d0 2023-10-14 (66) 63MB -
  latest/candidate: ↑                                  
  latest/beta:      ↑                                  
  latest/edge:      0+git.cfe32d0 2023-10-13 (66) 63MB -
installed:          0+git.cfe32d0            (66) 63MB -

 soumyaxubuntu  soumyas-gf63-thin-11uc  ~  ls /snap/ffmpeg-2204-sdk/current/usr/lib/x86_64-linux-gnu/pkgconfig/
drwxr-xr-x 2 root root  305 2023-10-14 00:41 .
drwxr-xr-x 5 root root 4.6K 2023-10-14 00:41 ..
-rw-r--r-- 1 root root  335 2023-10-14 00:41 avisynth.pc
-rw-r--r-- 1 root root  251 2023-10-14 00:41 dav1d.pc
-rw-r--r-- 1 root root  186 2023-10-14 00:41 ffnvcodec.pc
-rw-r--r-- 1 root root  357 2023-10-14 00:41 haisrt.pc
-rw-r--r-- 1 root root  855 2023-10-14 00:41 libavcodec.pc
-rw-r--r-- 1 root root  685 2023-10-14 00:41 libavdevice.pc
-rw-r--r-- 1 root root  794 2023-10-14 00:41 libavfilter.pc
-rw-r--r-- 1 root root  541 2023-10-14 00:41 libavformat.pc
-rw-r--r-- 1 root root  399 2023-10-14 00:41 libavutil.pc
-rw-r--r-- 1 root root  354 2023-10-14 00:41 libpostproc.pc
-rw-r--r-- 1 root root  367 2023-10-14 00:41 libswresample.pc
-rw-r--r-- 1 root root  352 2023-10-14 00:41 libswscale.pc
-rw-r--r-- 1 root root  357 2023-10-14 00:41 srt.pc
-rw-r--r-- 1 root root  331 2023-10-14 00:41 x264.pc
-rw-r--r-- 1 root root  414 2023-10-14 00:41 zimg.pc
```

And as you can see, it's in the folder needed. Can you show me which build is failing?

**Comment by iomezk** [comment]
It can depend on environment. I use jammy lxd container with --destructive

**Comment by soumyaDghosh** [comment]
Can you give me the manifest, that you're facing the above mentioned error while building? Did you add the `ffmpeg-2204-sdk` as build-snaps?

**Comment by iomezk** [comment]
It was latest commit (cfe32d0) of ffmpeg-2204-sdk branch
Full snapcraft log https://pastebin.com/ryGN31Ef line 2060

**Comment by soumyaDghosh** [comment]
I am not sure why is this happening. But, I can't find any reason, of you building it in your machine/locally building by self. Also, as you may have known from the forum, this repo will soon be under the snapcrafters umbrella. So, I think you should wait. What's problem in using this snap as it is?

**Comment by iomezk** [comment]
At least, I could check ffmpeg 6.1

**Comment by soumyaDghosh** [comment]
Okay, I updated to release/6.1 branch. Wait some hours, it'll be in the edge

**Comment by iomezk** [comment]
At first look vulkan shouldn't be usable because there is no https://packages.ubuntu.com/jammy-updates/amd64/mesa-vulkan-drivers/filelist

**Comment by soumyaDghosh** [comment]
`mesa-core22` and others are there for it. So, I left it as it is.

**Comment by soumyaDghosh** [comment]
Not planned for now

**Pull request closed without merging**
